### ISSUE TITLE
Analyzer Error on https://pub.green/packages/google_nav_bar

### ISSUE THREAD

**Issue by sooxt98** [sooxt98/google_nav_bar#50]

**Comment by sooxt98** [comment]
@Ascenio Im not sure why its giving error after null-safety could you help me check it out?

**Comment by Ascenio** [comment]
So, the error was generated after trying to execute the test `google_nav_bar_test.dart`, because it has been commented the command `flutter test` can't run it. The easy fix is to simply remove the tests folder, as there are no tests anyway. However, I don't know if pub.green will complain if there are no tests.

**Comment by Ascenio** [comment]
Actually taking a look again I realized that version 4.0.2 had no tests but still passed as green. So maybe that's the solution.

**Comment by sooxt98** [comment]
@Ascenio oh thanks I'll try to delete that test folder see if it fix

**Comment by sooxt98** [comment]
@Ascenio after some digging, i think this is their issue; something misconfigure at their `/Users/builder/clone/analysis_options.yaml` files, I'll try to email them 

![image](https://user-images.githubusercontent.com/13378059/111029201-4ffccc80-8436-11eb-82bb-090e55231c48.png)

**Comment by Ascenio** [comment]
If you take a look at their dashboard you see accusing problems with tests
![](https://imgur.com/7evKqrF.png)
So I clicked to see the logs of tests
![](https://imgur.com/P4zgf3a.png)
And it shows a error because the test file doesn't have a main.
![](https://imgur.com/YtRYoBK.png)
I tested it myself locally with `flutter test` and the result was similar to theirs.

**Comment by sooxt98** [comment]
@Ascenio thanks, i have added `google_nav_bar_test.dart` which fix the issue
